{{- if not .Values.cluster.managed }}
{{- $localStorageClass := .Values.cluster.storageClasses.local -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $localStorageClass }}
  labels:
    app: {{ $localStorageClass }}
provisioner: k8s.io/microk8s-hostpath
volumeBindingMode: Immediate
{{- end }}
