cluster:
  namespace: federation-handson
  managed: true
  storageClasses:
    local: k8s-local-storage
    managed: ceph-corbo-cephfs
network:
  externalIP: ""
  link: proxied
  externalProtocol: https
  publicProtocol: https
  publicHost: handson.hbpmip.link
  ingress:
    enabled: true
    className: nginx-public
    certManagerClusterIssuer: letsencrypt-public
    tlsSecretName: platform-ui-tls
    redirectRootTo: /home
engines:
  exaflow:
    url: "http://exaflow-controller-service:5000"
    image:
      repository: madgik/exaflow
      tag: 1.0.0
mip:
  displayName: MIP
  version: 9.0.0
datacatalog:
  protocol: https
  host: ""
platform-ui:
  image:
    repository: hbpmip/platform-ui
    tag: 1.0.0
  service:
    nodePort: 30080
  ingress:
    enabled: true
    className: nginx-public
    certManagerClusterIssuer: letsencrypt-public
    tlsSecretName: platform-ui-tls
  backend:
    host: platform-backend-service
    port: 8080
    context: services
  config:
    errorLogLevel: ERROR
    datacatalog:
      protocol: https
      host: ""
    matomo:
      enabled: false
      url: ""
      siteId: ""
platform-backend:
  image:
    repository: hbpmip/platform-backend
    tag: 9.0.0
  config:
    logLevel: INFO
    logLevelFramework: INFO
    algorithmUpdateInterval: 60
  persistence:
    data:
      localPath: /opt/mip-deployment/config
      size: 100Mi
    logs:
      localPath: /opt/mip-deployment/logs
      size: 1Gi

platformBackendDatabase:
  image:
    repository: postgres
    tag: 11.3-alpine
  persistence:
    localPath: /opt/mip-deployment/.stored_data/platform_backenddb
    size: 1Gi
keycloak:
  enabled: true
  host: iam.ebrains.eu
  protocol: https
  realm: MIP
  clientId: mipfedqa
  sslRequired: external
  proxyAddressForwarding: true
