name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  portal-backend-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install docker compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '5.1.0'

      - name: Docker compose version
        run: docker compose version

      - name: Copy the env file
        working-directory: ./deployment/dev/
        run: cp .env.example .env

      - name: Deploy the stack
        working-directory: ./deployment/dev/
        run: bash start.sh

      - name: Get deployment status
        run: docker ps

      - name: Install python dependencies
        working-directory: ./deployment/dev/
        run: pip install -r requirements.txt

      - name: Run the integration tests
        working-directory: ./deployment/dev/
        run: pytest
